import { AuditApprovalInvalidAttemptAction } from "../actions/audit-approval-invalid-attempt.action";
import { ApproveApprovalRecordAction } from "../actions/approve-approval-record.action";
import { CreateApprovalRecordAction } from "../actions/create-approval-record.action";
import { EscalateCoAction } from "../actions/escalate-co.action";
import { CheckTaskAction } from "../actions/check-task.action";
import { CreatePmsTaskAction } from "../actions/create-pms-task.action";
import { CreateDefectTaskAction } from "../actions/create-defect-task.action";
import { MarkComplianceAction } from "../actions/mark-compliance.action";
import { MarkPmsTaskOverdueAction } from "../actions/mark-pms-task-overdue.action";
import { EscalateDefectToLogComdAction } from "../actions/escalate-defect-to-log-comd.action";
import { EscalateDefectToMccAction } from "../actions/escalate-defect-to-mcc.action";
import { NotifyMeoAction } from "../actions/notify-meo.action";
import { NotifyApprovalOwnerAction } from "../actions/notify-approval-owner.action";
import { NotifyPmsSupervisorAction } from "../actions/notify-pms-supervisor.action";
import { RejectApprovalRecordAction } from "../actions/reject-approval-record.action";
import { ReplanPmsTaskAction } from "../actions/replan-pms-task.action";
import { SubmitApprovalRecordAction } from "../actions/submit-approval-record.action";
import { EngineEvent } from "./types";
import { type CoReport, type MeoReport, type WeoReport } from "./reporting";
import { InMemoryStore } from "./store";
import { ApprovalRule } from "../rules/approval.rule";
import { DailyLogRule } from "../rules/daily-log.rule";
import { DefectRule } from "../rules/defect.rule";
import { PmsTaskRule } from "../rules/pms-task.rule";
import { EventBus } from "../events/event-system";
interface EngineDependencies {
    store: InMemoryStore;
    approvalRule: ApprovalRule;
    dailyLogRule: DailyLogRule;
    pmsTaskRule: PmsTaskRule;
    defectRule: DefectRule;
    auditApprovalInvalidAttemptAction: AuditApprovalInvalidAttemptAction;
    createApprovalRecordAction: CreateApprovalRecordAction;
    submitApprovalRecordAction: SubmitApprovalRecordAction;
    approveApprovalRecordAction: ApproveApprovalRecordAction;
    rejectApprovalRecordAction: RejectApprovalRecordAction;
    notifyApprovalOwnerAction: NotifyApprovalOwnerAction;
    markComplianceAction: MarkComplianceAction;
    notifyMeoAction: NotifyMeoAction;
    escalateCoAction: EscalateCoAction;
    checkTaskAction: CheckTaskAction;
    createPmsTaskAction: CreatePmsTaskAction;
    createDefectTaskAction: CreateDefectTaskAction;
    markPmsTaskOverdueAction: MarkPmsTaskOverdueAction;
    replanPmsTaskAction: ReplanPmsTaskAction;
    notifyPmsSupervisorAction: NotifyPmsSupervisorAction;
    escalateDefectToMccAction: EscalateDefectToMccAction;
    escalateDefectToLogComdAction: EscalateDefectToLogComdAction;
    eventBus: EventBus;
}
export declare class ComplianceEngine {
    private readonly dependencies;
    private readonly unsubscribe;
    private lastEventKey;
    private lastEventAtMs;
    constructor(dependencies: EngineDependencies);
    routeEvent(event: EngineEvent): boolean;
    stop(): void;
    getMeoReport(shipId: string): MeoReport;
    getWeoReport(shipId: string): WeoReport;
    getCoReport(): CoReport;
    private dispatch;
    private evaluate;
    private assertEventContext;
    private assertInputGuard;
    private getEventValidationError;
    private assertCommandContext;
    private isDuplicateEvent;
    private refreshComplianceSignals;
    private mergeSignals;
    private buildSignalKey;
    private compareSignals;
    private compareSeverity;
    private severityRank;
    private compareOptionalString;
    private buildReadModelState;
    private resolveEventIntegrityId;
    private toInputGuardEvent;
    private buildInputGuardState;
    private getDeterministicEventPayload;
    private normalizeValue;
    private serializeDeterministicPayload;
}
export {};
//# sourceMappingURL=engine.d.ts.map