import type { ComplianceSignal } from "./compliance-engine";
import { ActorContext, ApprovalAwarenessQueryOptions, ApprovalAwarenessRecord, ApprovalHistoryType, ApprovalRecordView, AssignedRoleId, DailyComplianceState, Defect, Equipment, EscalationState, FleetRecord, LogRecord, LogType, Notification, RoleDashboardSummary, RoleId, Ship, StoreSnapshot, Task, TaskSnapshot } from "./types";
interface ProcessedApprovalTransition {
    recordId: string;
    actionType: ApprovalHistoryType;
}
export interface FailedEventRecord {
    eventId: string;
    reason: string;
    timestamp: number;
}
export interface StoreHealthCheck {
    running: boolean;
    totalTasks: number;
    overdueTasks: number;
    escalationCounts: {
        none: number;
        mcc: number;
        logComd: number;
    };
    perShip: Record<string, {
        totalTasks: number;
        overdueTasks: number;
        escalationCounts: {
            none: number;
            mcc: number;
            logComd: number;
        };
    }>;
    lastPersistenceTimestamp: string | null;
}
export declare class InMemoryStore {
    private readonly shipsById;
    private readonly equipmentByIss;
    private readonly logsByDate;
    private readonly complianceByDate;
    private readonly escalationByDate;
    private readonly tasksById;
    private readonly defectsById;
    private readonly taskHistoryById;
    private readonly recordsById;
    private readonly approvalHistoryById;
    private readonly processedTransitions;
    private readonly processedEventsById;
    private readonly failedEventsById;
    private readonly notificationsById;
    private readonly complianceSignalsByKey;
    private readonly persistenceFilePath;
    private readonly backupFilePath;
    private readonly tempFilePath;
    private lastPersistenceTimestamp;
    constructor(persistenceFilePath?: string);
    saveLog(record: LogRecord): void;
    saveEquipment(equipment: Equipment): Equipment;
    getEquipment(iss: string): Equipment | null;
    getAllEquipment(): Equipment[];
    getLogsForDate(shipId: string, businessDate: string): LogRecord[];
    getOrCreateComplianceState(shipId: string, businessDate: string): DailyComplianceState;
    updateComplianceState(shipId: string, businessDate: string, update: Partial<DailyComplianceState>): DailyComplianceState;
    getOrCreateEscalationState(shipId: string, businessDate: string): EscalationState;
    updateEscalationState(shipId: string, businessDate: string, update: Partial<EscalationState>): EscalationState;
    getSnapshot(shipId: string, businessDate: string): StoreSnapshot;
    createTask(task: Task, occurredAt: string, actor: RoleId): Task;
    createDefect(defect: Defect): Defect;
    getDefect(defectId: string): Defect | null;
    getAllDefects(): Defect[];
    getTasksByDefectId(defectId: string): Task[];
    getFailedEvents(): FailedEventRecord[];
    getFailedEventById(eventId: string): FailedEventRecord | null;
    updateDefectStatus(defectId: string, status: Defect["status"]): Defect;
    getTask(taskId: string): Task | null;
    getTaskInShip(taskId: string, shipId: string): Task | null;
    completeTask(taskId: string, occurredAt: string, actor: RoleId): Task;
    recordTaskCheck(taskId: string, occurredAt: string, actor: RoleId): Task;
    markTaskOverdue(taskId: string, occurredAt: string, actor: RoleId): Task;
    escalateTask(taskId: string, escalationLevel: "MCC" | "LOG_COMD", occurredAt: string, actor: RoleId): Task;
    replanTask(taskId: string, nextDueDate: string, occurredAt: string, actor: RoleId): Task;
    recordTaskNotification(taskId: string, occurredAt: string, actor: RoleId): Task;
    getTaskSnapshot(taskId: string): TaskSnapshot;
    getTaskSnapshotInShip(taskId: string, shipId: string): TaskSnapshot;
    createApprovalRecord(record: FleetRecord, occurredAt: string, actor: RoleId): FleetRecord;
    getApprovalRecord(recordId: string): FleetRecord | null;
    getApprovalRecordInShip(recordId: string, shipId: string): FleetRecord | null;
    getApprovalRecordViewInShip(recordId: string, shipId: string): ApprovalRecordView;
    getProcessedApprovalTransition(transitionId: string): ProcessedApprovalTransition | null;
    isEventProcessed(eventId: string): boolean;
    markEventProcessed(eventId: string, processedAt: number): void;
    recordFailedEvent(eventId: string, reason: string, timestamp: number): void;
    clearFailedEvent(eventId: string): void;
    cleanupFailedEvents(now: number, ttlMs: number): void;
    cleanupProcessedEvents(now: number, ttlMs: number): void;
    getPreviousApprovalOwnerInShip(recordId: string, shipId: string): AssignedRoleId;
    getApprovalRecordsByShip(shipId: string): FleetRecord[];
    getApprovalRecordsVisibleToRole(shipId: string, role: AssignedRoleId): FleetRecord[];
    getApprovalRecordViewVisibleToRole(recordId: string, shipId: string, role: AssignedRoleId): ApprovalRecordView;
    getApprovalRecordViewForActor(recordId: string, actor: ActorContext): ApprovalRecordView;
    getApprovalAwarenessRecords(actor: ActorContext, options?: ApprovalAwarenessQueryOptions): ApprovalAwarenessRecord[];
    getApprovalDashboardSummary(actor: ActorContext, options?: ApprovalAwarenessQueryOptions): RoleDashboardSummary;
    getTopActionableRecords(actor: ActorContext, limit?: number): ApprovalAwarenessRecord[];
    getTopStaleRecords(actor: ActorContext, limit?: number): ApprovalAwarenessRecord[];
    getRecentRejections(actor: ActorContext, limit?: number): ApprovalAwarenessRecord[];
    getStaleApprovalRecordsByShip(shipId: string, occurredAt: string, thresholdHours: number): FleetRecord[];
    submitApprovalRecord(recordId: string, shipId: string, occurredAt: string, actor: RoleId, transitionId: string, reason: string | null, note: string | null): FleetRecord;
    approveApprovalRecord(recordId: string, shipId: string, occurredAt: string, actor: RoleId, transitionId: string, reason: string | null, note: string | null): FleetRecord;
    rejectApprovalRecord(recordId: string, shipId: string, occurredAt: string, actor: RoleId, transitionId: string, reason: string | null, note: string | null): FleetRecord;
    getAllTasks(): Task[];
    getTasksByShip(shipId: string): Task[];
    getOverdueTasks(): Task[];
    getOverdueTasksByShip(shipId: string): Task[];
    saveShip(ship: Ship): Ship;
    getShip(shipId: string): Ship | null;
    getAllShips(): Ship[];
    createNotification(input: Omit<Notification, "id" | "read">): Notification;
    getNotifications(shipId: string, role: RoleId): Notification[];
    addComplianceSignals(signals: ComplianceSignal[]): void;
    getComplianceSignalsByShip(shipId: string): ComplianceSignal[];
    getAllComplianceSignals(): ComplianceSignal[];
    clearComplianceSignals(): void;
    markNotificationRead(notificationId: string): Notification;
    flush(): void;
    getHealthCheck(): StoreHealthCheck;
    seedDailyLogs(shipId: string, businessDate: string, logTypes: LogType[], submittedByRole?: "MARINE_ENGINEERING_OFFICER"): void;
    private normalizeAwarenessOptions;
    private normalizeActorContext;
    private requiresShipScopedVisibility;
    private resolveActorScopedShipId;
    private getVisibleApprovalRecordsForAwareness;
    private isRecordVisibleToActor;
    private projectApprovalAwarenessRecord;
    private resolveAwarenessBucket;
    private resolveAwarenessAttentionSignals;
    private isAwarenessRecordPendingTooLong;
    private isAwarenessRecordStale;
    private isRecentlyRejected;
    private resolveAwarenessPreviousOwner;
    private compareAwarenessRecords;
    private compareByAgeThenCreatedAt;
    private getAwarenessSortPriority;
    private getElapsedHours;
    private assertApprovalAwarenessRecords;
    private assertApprovalAwarenessSummary;
    private assertPositiveNumber;
    private assertPositiveInteger;
    private requireTask;
    private getDailyStateKey;
    private appendTaskHistory;
    private appendApprovalHistory;
    recordApprovalInvalidAttempt(recordId: string, shipId: string, occurredAt: string, actor: RoleId, transitionId: string | null, reason: string, note: string | null): void;
    recordApprovalStaleNotification(recordId: string, shipId: string, occurredAt: string, actor: RoleId): FleetRecord;
    private applyTaskUpdate;
    private createStateSnapshot;
    private createApprovalSnapshot;
    private isSameState;
    private isSameApprovalState;
    private isSameInterval;
    private isSameUsageTracking;
    private deriveNextDueAt;
    private deriveIntervalDueAt;
    private computeMinimalNextDueAt;
    private getMinimalIntervalMs;
    private convertIntervalToMs;
    private applyApprovalTransition;
    private assertTaskStatusTransition;
    private assertEscalationTransition;
    private isTerminalApprovalStatus;
    private assertApprovalRecordMutable;
    private assertValidRole;
    private assertValidAssignedRole;
    private assertValidShipId;
    private assertValidShip;
    private assertShipExists;
    private assertTaskEquipmentLinkage;
    private assertValidEquipment;
    private assertValidDefect;
    private loadPersistedState;
    private hydrateTask;
    private hydrateTaskHistoryEntry;
    private hydrateTaskStateSnapshot;
    private migrateTasks;
    private migrateTaskHistory;
    private migrateEquipment;
    private migrateDefects;
    private deriveExecutionStatus;
    private parseOptionalTimestamp;
    private tryLoadFromPath;
    private validatePersistedState;
    private tryMigratePersistedState;
    private isTask;
    private isEquipment;
    private isDefect;
    private isFleetRecord;
    private isShip;
    private isTaskHistoryTuple;
    private isTaskHistoryEntry;
    private isApprovalHistoryTuple;
    private isApprovalHistoryEntry;
    private isTaskStateSnapshot;
    private isApprovalRecordSnapshot;
    private isEscalationStateTuple;
    private isEscalationState;
    private isNotification;
    private isComplianceSignal;
    private isProcessedTransitionTuple;
    private isProcessedApprovalTransition;
    private buildNotificationDedupeKey;
    private isRoleId;
    private isAssignedRoleId;
    private isApprovalStatus;
    private isFleetRecordKind;
    private isTaskHistoryType;
    private isApprovalHistoryType;
    private isApprovalFlow;
    private assertValidFleetRecord;
    private getApprovalChainRole;
    private getPreviousApprovalOwner;
    private assertValidComplianceSignal;
    private buildComplianceSignalKey;
    private compareComplianceSignals;
    private compareComplianceSeverity;
    private getComplianceSeverityRank;
    private compareOptionalString;
    private getEventIntegrityState;
    private replaceProcessedEvents;
    private resetPersistedState;
    private persistState;
}
export {};
//# sourceMappingURL=store.d.ts.map